name = "fundraising-discord-bot"
main = "src/index.js"
compatibility_date = "2024-01-15"

[vars]
# Public environment variables (not secrets)
ENVIRONMENT = "production"

# Secrets are set separately with: wrangler secret put COMMAND
# - DISCORD_TOKEN
# - DISCORD_PUBLIC_KEY  
# - DISCORD_APPLICATION_ID
# - NEXT_PUBLIC_APP_URL